const Map<String, String> ar = {
  "startLearning": "ابدأ التعلم",
  "exploreMaps": "تصفح الخرائط",
  "challengeYourself": "اختبر معلوماتك",
  "aboutUs": "من نحن",
  "chooseALanguage": "اختر اللغة:",
  "mainPageTitle": "المحافظات العراقية",
  "mainPageSubtitle": "خريطة تفاعلية لتجربة تعليمية ممتعة",

  // CapitalCity Titles
  "Dihok":"دهوك",
  "Hewlêr":"هولير",
  "Samawah":"السماوة",
  "Silêmanî":"السليمانية",
  "Baqubah":"بعقوبة",
  "Kut":"الكوت",
  "Amarah":"العمارة",
  "Ramadi":"الرمادي",
  "Mosul":"الموصل",
  "Tikrit":"تكريت",
  "Kerkûk": "كركوك",
  "Hillah": "الحلة",
  "Al Diwaniyah": "الديوانية",
  "Nasiriyah": "الناصرية",

  // Provinces Titles
  "Iraqi Provinces":"المحافظات العراقية",
  "Baghdad":"بغداد",
  "Duhok":"دهوك",
  "Erbil":"اربيل",
  "Basra":"البصرة",
  "Muthanna":"المثنى",
  "Sulaymaniyah":"السليمانية",
  "Diyala":"ديالى",
  "Wasit":"واسط",
  "Maysan":"ميسان",
  "Al-Anbar":"الانبار",
  "Najaf":"النجف",
  "Ninawa":"نينوى",
  "Salah Al-Din":"صلاح الدين",
  "Kirkuk": "كركوك",
  "Babil": "بابل",
  "Al-Qadisiyyah": "القادسية",
  "Dhi Qar": "ذي قار",
  "Karbala": "كربلاء المقدسة",

  // Details Screen
  "Km2": " كم مربع",
  "Area:":"المساحة:",
  "Population:":"التعداد السكاني:",
  "Capital:":"مركز المحافظة:",
  "Interesting Fact:":"حقيقة مثيرة للاهتمام:",
  "moreInfo":"المزيد من المعلومات التاريخية",

  // Exam Screen
  "completed":" اكتمل",
  "showResults":"عرض النتائج",
  "next":"التالي",
};