const Map<String, String> en = {
  "startLearning": "Start Learning",
  "exploreMaps": "Explore Maps",
  "challengeYourself": "Challenge yourself",
  "aboutUs": "About us",
  "chooseALanguage": "Choose a language:",
  "iraqMap": "Iraq Map",
  "mainPageSubtitle": "Interactive map for enjoyable learning experience",

  // Provinces Titles
  "Iraqi Provinces":"Iraqi Provinces",
  "Baghdad":"Baghdad",
  "Duhok":"Duhok",
  "Erbil":"Erbil",
  "Basra":"Basra",
  "Muthanna":"Muthanna",
  "Sulaymaniyah":"Sulaymaniyah",
  "Diyala":"Diyala",
  "Wasit":"Wasit",
  "Maysan":"Maysan",
  "Al-Anbar":"Al-Anbar",
  "Najaf":"Najaf",
  "Ninawa":"Ninawa",
  "Salah Al-Din":"Salah Al-Din",
  "Kirkuk": "Kirkuk",
  "Babil": "Babil",
  "Al-Qadisiyyah": "Al-Qadisiyyah",
  "Dhi Qar": "Dhi Qar",
  "Karbala": "Karbala",

  // Details Screen
  "Km2": " Km2",
  "Area:":"Area:",
  "Population:":"Population:",
  "Capital:":"Capital:",
  "Interesting Fact:":"Interesting Fact:",
  "moreInfo":"More Detailed Historical Info",
};