const Map<String, String> en = {
  "startLearning": "Start Learning",
  "exploreMaps": "Explore Maps",
  "challengeYourself": "Challenge yourself",
  "aboutUs": "About us",
  "chooseALanguage": "Choose a language:",
  "mainPageTitle": "Iraqi Provinces",
  "mainPageSubtitle": "Interactive map for enjoyable learning experience",

  // Provinces Titles
  "Iraqi Provinces":"Iraqi Provinces",
  "Baghdad":"Baghdad",
  "Duhok":"Duhok",
  "Erbil":"Erbil",
  "Basra":"Basra",
  "Muthanna":"Muthanna",
  "Sulaymaniyah":"Sulaymaniyah",
  "Diyala":"Diyala",
  "Wasit":"Wasit",
  "Maysan":"Maysan",
  "Al-Anbar":"Al-Anbar",
  "Najaf":"Najaf",
  "Ninawa":"Ninawa",
  "Salah Al-Din":"Salah Al-Din",
  "Kirkuk": "Kirkuk",
  "Babil": "Babil",
  "Al-Qadisiyyah": "Al-Qadisiyyah",
  "Dhi Qar": "Dhi Qar",
  "Karbala": "Karbala",

  // CapitalCity Titles
  "Dihok":"Dihok",
  "Hewlêr":"Hewlêr",
  "Samawah":"Samawah",
  "Silêmanî":"Silêmanî",
  "Baqubah":"Baqubah",
  "Kut":"Kut",
  "Amarah":"Amarah",
  "Ramadi":"Ramadi",
  "Mosul":"Mosul",
  "Tikrit":"Tikrit",
  "Kerkûk": "Kerkûk",
  "Hillah": "Hillah",
  "Al Diwaniyah": "Al Diwaniyah",
  "Nasiriyah": "Nasiriyah",

  // Details Screen
  "Km2": " Km2",
  "Area:":"Area:",
  "Population:":"Population:",
  "Capital:":"Capital:",
  "Interesting Fact:":"Interesting Fact:",
  "moreInfo":"More Detailed Historical Info",
  "moreAbout":"Enjoy reading more about ",

  // StartExam Screen
  "startExamTitle":"Are you up for a challenge? Test your knowledge of Iraq by taking this multiple-choice quiz!",
  "chooseNumberOfQuestions":"Select a number of questions ranging from 5 to 25.",
  "startQuiz":"Start Quiz",

  // Exam Screen
  "completed":" Completed",
  "showResults":"Show Results",
  "next":"Next",
};